### ISSUE TITLE
Released tar.gz should include correct stgit/builtin_version.py

### ISSUE THREAD

**Issue by Necoro** [ctmarinas/stgit#25]
The current setup.py tries to read the version it is installing from the git repository. This, naturally, does not work when installing from the tarball. As a consequence, stgit reports 'unkown-version'.

**Fix:** Add the correct builtin_version.py to the tarball and remove the call to write_builtin_version from the released setup.py.

**Comment by jpgrayson** [comment]
This is repaired in v0.19.

The release archives (tar.gz and zip) now contain a `.git_archival.txt` file. This file is a template that is formatted by git/GitHub to contain the refs associated with the archive when the archive is created.

When running `setup.py` from an unpacked archive, `.git_archival.txt` will be parsed for tags. The first matching tag will be used for the version.

N.B. this mechanism will only work for archives coming from tags. For untagged archives, `setup.py` will fail to determine the version. This is because the information in `.git_archival.txt` is insufficient to derive the same kind of inter-tag version information available from `git describe` such as the last tag or the number of commits since the last tag.
