### ISSUE TITLE
stgit 0.21 tar checksum changed

### ISSUE THREAD

**Issue by iMichka** [ctmarinas/stgit#52]
Hi. Homebrew maintainer here.

The checksum of your 0.21 archive changed. Did somebody do something malicious with your account and hijacked your artifacts?

```
==> Downloading https://github.com/ctmarinas/stgit/archive/v0.21.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: ba1ccbbc15beccc4648ae3b3a198693be7e6b1b1e330f45605654d56095dac0d
  Actual: 67a5b93c832e8ce1349afbddca93d834fc6f78ae8fd9e45c99206dc87eb3440c
```

For reference: https://github.com/Homebrew/linuxbrew-core/pull/19745

**Comment by jpgrayson** [comment]
Hi @iMichka. Thanks for pointing out this issue and thanks for working on the Homebrew packaging for StGit; and especially for migrating the Homebrew packaging from Python 2 to 3.

This problem came up a while ago with the Arch Linux packaging for stgit. Reference:

https://aur.archlinux.org/packages/stgit/#comment-671581
https://aur.archlinux.org/packages/stgit/#comment-671286

The core problem is that the github generated "Source Code" archives, such as the one `stgit.rb` links to, are not deterministic.

The solution is to not rely on the github generated archives. When making StGit releases, I generate and post a stgit-X.Y.tar.gz that _is_ stable and has a stable hash.

https://github.com/ctmarinas/stgit/releases/download/v0.21/stgit-0.21.tar.gz

So I propose that the Homebrew formula be updated to use the above tarball.

And I just double-checked that the sha256 hash of the above remains as expected:

`0f67a3c0ed3e0408aa8e9be6ff6c7be0a2981ca43639bc94bda7b6124717e71f`

And while I have your attention, I will note that Homebrew's `stgit.rb` forumula does not seem to install the shell completions (bash, fish, and zsh) or man pages. It would be nice if those were installed by the formula.

Thanks again!

**Comment by iMichka** [comment]
Thanks for the quick reply. 99% of checksum mismatches we see are git tags being moved after a release. But you are right, it's not the first time we have this issue with GitHub archives (I should have noticed, as it is also a quite common issue).

I updated the url here, this will be merged as soon as possible: https://github.com/Homebrew/homebrew-core/pull/51075

Regarding the completions and man pages, anybody can open a pull request to add these.

I am currently focusing on migrating most of our libraries to Python 3 only, this is why I stumbled over stgit and the broken checksum. I'll let other volunteers take over the completions and man page change.

Thank you for your help.
