### ISSUE TITLE
Nit: 0.22 "stg edit --sign" is broken with older versions of git

### ISSUE THREAD

**Issue by chucklever** [ctmarinas/stgit#54]
I decided to replace the EPEL 7 version of stgit on my RHEL 7 system with the latest upstream stgit. Things mostly work, but this happened this morning:

```
[cel@klimt linux]$ stg edit --sign
git: 'interpret-trailers' is not a git command. See 'git --help'.
stg edit: git failed with code 1
[cel@klimt linux]$ stg version
Stacked GIT 0.22
git version 1.8.3.1
Python version 2.7.5 (default, Apr 11 2018, 17:41:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)]
[cel@klimt linux]$
```

A newer version of git is not available through RHEL 7 channels, but I can build and use an upstream copy on this system.

**Comment by jpgrayson** [comment]
`git interpret-trailers` was added in git 2.2.0 which was released in November, 2014.
RHEL7's git 1.8.3.1 was released in June, 2013.

There is only so much maintenance bandwidth available for StGit. Most of my recent efforts have been to lessen the StGit maintenance burden. Changes to that end include:

* Fully migrating all StGit commands to "new" git library. (Done as of StGit 0.22)
* Normalize coding conventions and add lint to CI
* Drop support for Python 2.x (in-progress, coming next release)
* Replace StGit code with git-native commands

StGit's custom code for editing commit message trailers was a victim of that last bullet. Using `git interpret-trailers` was a little less code and may help with correctness.

I can appreciate RHEL's value proposition of stability and security, but when this kind of compatibility issue arises, my feeling is that an upstream project, like StGit, is not necessarily the right place to solve it. Although RedHat's business model is stability (extremely minimal changes to packages), upstream projects need to change to survive. So it is not tenable for StGit to change without changing.

In this particular case, the old behavior could be restored relatively easily by reverting a single commit, but I nonetheless remain hesitant to take that course. My sense is that the next issue will be that RHEL 7 doesn't support Python 3, or only supports a particularly old Python3, or there will be some other subtle git incompatibility...point being, the StGit maintainers (mostly just me) do not have the energy or motivation to ferret out compatibility issues with relatively old OS platforms, versions of Git, or versions of Python.

Please also note that I am not saying this as any sort of admonishment. I appreciate this issue report. My hope is to establish a sort of policy statement about StGit. An action I will take is to clarify this policy in StGit's documentation (README, tutorial, etc.) and to update StGit's known minimum git version so that this kind of problem can be caught at initialization-time instead of deeper into runtime as happens in this case. I will leave this issue open until I can get those bits into place.

**Comment by chucklever** [comment]
Given that RHEL 7 doesn't even package stgit (it comes in via EPEL,) I completely understand how it would be difficult to make anyone care about my odd combination of git and stgit versions. In fact, I installed the latest stgit to prepare for tracking down other issues; otherwise I would have stayed with 0.17-dirty.

For the record, replacing RHEL 7's git with 2.26.0.rc1.11.g30e9940356dc does address the problem. Thanks for your response, and please close this issue when you see fit.
